---
title: "party-change"
output: html_document
date: "2025-12-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## R Markdown

# Load necessary libraries
```{r}
install.packages("tidyr") 
install.packages("writexl")
install.packages("data.table")
install.packages("knitr")
library(data.table)
library(knitr)
library (writexl)
library(tidyr)
```

```{r}
# Load necessary library
library(dplyr)
 
```  


```{r}
#statewide voter registration file found here: https://www.ncsbe.gov/results-data/voter-registration-data. File was pulled on Dec. 18 

library(data.table)

zip_url <- "https://s3.amazonaws.com/dl.ncsbe.gov/data/ncvoter_Statewide.zip"
zip_path <- tempfile(fileext = ".zip")

download.file(zip_url, zip_path, mode = "wb")

# See what's inside the zip
contents <- unzip(zip_path, list = TRUE)
contents

csv_path <- unzip(zip_path, files = contents$Name[1])  
file.info(csv_path)$size

voter_file <- fread(
  csv_path,
  sep = "\t",
  encoding = "UTF-8",
  showProgress = TRUE
)

nrow(voter_file)
ncol(voter_file) 
```


```{r}
# Removing inactive and removed
voter_file_cleared <- voter_file[!voter_status_desc %in% c("REMOVED", "INACTIVE")]
```

```{r}

# party change file pulled from here: https://dl.ncsbe.gov/?prefix=data/PartyChange/ 

# pulled the file from 12/1/2025, 6:00:43 AM.  

url <- "https://s3.amazonaws.com/dl.ncsbe.gov/data/PartyChange/2025_party_change_list.csv"

party_change <- read.csv(
  url,
  stringsAsFactors = FALSE,
  fileEncoding = "UTF-8"
)


#colnames(party_change) 

``` 

```{r}
# joining the voter registration file with the party change file via the county and voter registration number. 
library(data.table)

setDT(voter_file)
setDT(party_change)

voter_party_only <- voter_file[
  party_change,
  on = .(county_desc = county_name, voter_reg_num),
  nomatch = 0
]

colnames(voter_party_only) 
setcolorder(
  voter_party_only,
  c("year_change", "party_from", "party_to", "change_dt",
    setdiff(names(voter_party_only),
            c("year_change", "party_from", "party_to", "change_dt")))
)


``` 

```{r}
# Take all candidates and grabbing just by unique
candidates <- fread("./Candidate_Listing_2026 (8).csv", encoding = "UTF-8")

setDT(candidates)

candidates[, name_on_ballot := toupper(trimws(name_on_ballot))]
candidates[, county_name := toupper(trimws(county_name))]
candidates[, contest_name := toupper(trimws(contest_name))]

total_counties <- uniqueN(candidates$county_name)

candidates_unique <- candidates[
  ,
  {
    row <- .SD[1]

    cand_counties <- sort(unique(na.omit(county_name)))

    row$county_name <- if (length(cand_counties) == total_counties) {
      "ALL COUNTIES"
    } else {
      paste(cand_counties, collapse = ", ")
    }

    row$contest_name <- paste(
      sort(unique(na.omit(contest_name))),
      collapse = ", "
    )

    row
  },
  by = name_on_ballot
]

nrow(candidates_unique)
candidates_unique[1:10, .(name_on_ballot, county_name, contest_name)]




```

```{r}

library(data.table)

setDT(candidates_unique)
setDT(voter_party_only)


norm_name <- function(x) toupper(gsub("\\s+", " ", trimws(x)))

candidates_unique[, `:=`(
  first_name     = norm_name(first_name),
  last_name      = norm_name(last_name),
  county_name    = norm_name(county_name),
  contest_name   = norm_name(contest_name),
  name_on_ballot = norm_name(name_on_ballot)
)]

voter_party_only[, `:=`(
  first_name  = norm_name(first_name),
  last_name   = norm_name(last_name),
  county_desc = norm_name(county_desc)
)]

all_counties <- sort(unique(voter_party_only$county_desc))

cand_expanded <- candidates_unique[
  ,
  .(
    county_name = county_name,
    county_desc = if (county_name == "ALL COUNTIES") all_counties
                 else unlist(strsplit(county_name, "\\s*,\\s*"))
  ),
  by = .(name_on_ballot, first_name, last_name, contest_name)
]
cand_expanded[, county_desc := norm_name(county_desc)]

candidate_party_exact <- voter_party_only[
  cand_expanded,
  on = .(county_desc, first_name, last_name),
  nomatch = 0,
  allow.cartesian = TRUE
]

key_cols <- c(
  "name_on_ballot",
  "first_name",
  "last_name",
  "county_name",
  "county_desc",
  "contest_name"
)

setcolorder(
  candidate_party_exact,
  c(key_cols, setdiff(names(candidate_party_exact), key_cols))
)

candidate_party_exact[1:20]

colnames(candidate_party_exact)

```

```{r}
#more exact with party from == party
library(data.table)

setDT(candidates_unique)
setDT(voter_party_only)


norm_name <- function(x) toupper(gsub("\\s+", " ", trimws(x)))

candidates_unique[, `:=`(
  first_name     = norm_name(first_name),
  last_name      = norm_name(last_name),
  county_name    = norm_name(county_name),
  contest_name   = norm_name(contest_name),
  name_on_ballot = norm_name(name_on_ballot),
  party_candidate = norm_name(party_candidate)
)]

voter_party_only[, `:=`(
  first_name  = norm_name(first_name),
  last_name   = norm_name(last_name),
  county_desc = norm_name(county_desc),
  party_to    = norm_name(party_to), 
  party_from  = norm_name(party_from)
)]


all_counties <- sort(unique(voter_party_only$county_desc))


cand_expanded <- candidates_unique[
  ,
  .(
    county_name = county_name,
    party_candidate = party_candidate,
    county_desc = if (county_name == "ALL COUNTIES") all_counties
                 else unlist(strsplit(county_name, "\\s*,\\s*"))
  ),
  by = .(name_on_ballot, first_name, last_name, contest_name)
]
cand_expanded[, county_desc := norm_name(county_desc)]


candidate_party_exact2 <- voter_party_only[
  cand_expanded,
  on = .(county_desc, first_name, last_name),
  nomatch = 0,
  allow.cartesian = TRUE
]


candidate_party_exact2 <- candidate_party_exact2[
  party_to == party_candidate
]


candidate_party_exact2 <- candidate_party_exact2[party_from != party_to & party_to == party_candidate]


key_cols <- c(
  "name_on_ballot",
  "first_name",
  "last_name",
  "county_name",
  "county_desc",
  "contest_name",
  "party_candidate",
  "party_from",
  "party_to",
  "change_dt",
  "year_change",
  "voter_reg_num",
  "ncid"
)


key_cols <- key_cols[key_cols %in% names(candidate_party_exact2)]

setcolorder(
  candidate_party_exact2,
  c(key_cols, setdiff(names(candidate_party_exact2), key_cols))
)


nrow(candidate_party_exact2)
candidate_party_exact2[1:20]
```


```{r}
# Download in csv format. 
library(data.table)

fwrite(
  candidate_party_exact2,
  "candidates_party_change2026.csv"
)

getwd()
``` 
